"""Presentation layer for the validation dashboard.

Injects the AlgoControl/index.html visual language while leaving app.py's
widgets, data, charts, callbacks, and theme toggle functional.
"""

from __future__ import annotations

import streamlit as st


DARK = r"""
:root{--ac-bg:#0a0e14;--ac-surface:#111720;--ac-surface2:#161d28;--ac-surface3:#1a2230;--ac-border:#1f2a3a;--ac-border-hi:#2a3545;--ac-text:#e6edf3;--ac-muted:#8b98a8;--ac-soft:#5a6675;--ac-accent:#22d3ee;--ac-green:#10b981;--ac-red:#ef4444;--ac-amber:#f59e0b;--ac-purple:#a78bfa;--ac-shadow:rgba(0,0,0,.42)}
"""

LIGHT = r"""
:root{--ac-bg:#f6f8fb;--ac-surface:#fff;--ac-surface2:#eef2f7;--ac-surface3:#e5ebf3;--ac-border:#e2e8f0;--ac-border-hi:#cbd5e1;--ac-text:#0f172a;--ac-muted:#64748b;--ac-soft:#94a3b8;--ac-accent:#0891b2;--ac-green:#059669;--ac-red:#dc2626;--ac-amber:#d97706;--ac-purple:#7c3aed;--ac-shadow:rgba(15,23,42,.12)}
"""

CSS = r"""
html,body,.stApp,[data-testid="stAppViewContainer"]{background:var(--ac-bg)!important;color:var(--ac-text)!important;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}
.stApp{background-image:radial-gradient(900px 400px at 0% 0%,color-mix(in srgb,var(--ac-accent) 16%,transparent),transparent 60%),radial-gradient(760px 500px at 100% 0%,color-mix(in srgb,var(--ac-purple) 15%,transparent),transparent 58%),linear-gradient(135deg,var(--ac-bg),var(--ac-surface2))!important;background-attachment:fixed}
/* Keep Streamlit's sidebar toggle accessible. Hiding the whole header makes a collapsed sidebar impossible to restore. */
[data-testid="stHeader"]{visibility:visible!important;height:2.75rem!important;background:transparent!important;z-index:20!important}[data-testid="stToolbar"],#MainMenu,footer{visibility:hidden!important;height:0!important}
[data-testid="stHeader"] button{color:var(--ac-text)!important;background:var(--ac-surface2)!important;border:1px solid var(--ac-border)!important;border-radius:7px!important;box-shadow:0 2px 10px var(--ac-shadow)!important}
[data-testid="stAppViewContainer"]>.main .block-container{max-width:1520px!important;padding:1.25rem 2.2rem 3rem!important}*{box-sizing:border-box}
.term-header{display:flex;align-items:center;gap:18px;padding:4px 0 18px;margin-bottom:22px;border-bottom:1px solid var(--ac-border);position:relative}.term-header:after{content:"";position:absolute;left:0;bottom:-1px;width:220px;height:1px;background:linear-gradient(90deg,var(--ac-accent),transparent)}
.brand{display:flex;align-items:center;gap:12px;flex:1}.brand-mark{width:40px;height:40px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(135deg,var(--ac-accent),var(--ac-purple));color:#06121a;font-size:20px;font-weight:800;box-shadow:0 0 24px color-mix(in srgb,var(--ac-accent) 45%,transparent),0 0 44px color-mix(in srgb,var(--ac-purple) 18%,transparent)}.brand-title{font-size:15px;font-weight:800;letter-spacing:.06em;line-height:1.15;color:var(--ac-text)!important;white-space:nowrap}.brand-sub{font-size:11px;color:var(--ac-muted)!important;margin-top:3px}
.status-chip{display:inline-flex;align-items:center;gap:7px;padding:5px 12px;border-radius:999px;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.status-ok{color:var(--ac-green);background:color-mix(in srgb,var(--ac-green) 13%,transparent);border:1px solid color-mix(in srgb,var(--ac-green) 35%,transparent);box-shadow:0 0 16px color-mix(in srgb,var(--ac-green) 22%,transparent)}.status-alert{color:var(--ac-red);background:color-mix(in srgb,var(--ac-red) 13%,transparent);border:1px solid color-mix(in srgb,var(--ac-red) 35%,transparent);box-shadow:0 0 18px color-mix(in srgb,var(--ac-red) 25%,transparent)}.status-dot{width:6px;height:6px;border-radius:50%;background:currentColor;box-shadow:0 0 8px currentColor}
.info-banner{padding:17px 21px;border-radius:14px;background:linear-gradient(125deg,color-mix(in srgb,var(--ac-accent) 15%,transparent),color-mix(in srgb,var(--ac-purple) 5%,transparent) 55%,transparent 85%);border:1px solid color-mix(in srgb,var(--ac-accent) 26%,transparent);border-left:3px solid var(--ac-accent);margin-bottom:20px;box-shadow:0 8px 28px var(--ac-shadow),inset 0 1px 0 rgba(255,255,255,.04)}.info-eyebrow,.section-eyebrow{font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--ac-accent)!important;margin-bottom:7px}.info-body{font-size:13px;line-height:1.65;color:var(--ac-text)!important}.info-foot,.section-copy{font-size:11px;line-height:1.55;color:var(--ac-muted)!important;margin-top:8px}.section-title{font-size:15px;font-weight:750;color:var(--ac-text)!important;line-height:1.3}
[data-testid="stVerticalBlockBorderWrapper"]{background:linear-gradient(145deg,color-mix(in srgb,var(--ac-surface2) 72%,transparent),var(--ac-surface))!important;border:1px solid var(--ac-border)!important;border-radius:14px!important;box-shadow:0 10px 30px var(--ac-shadow),inset 0 1px 0 rgba(255,255,255,.035)!important;transition:box-shadow .2s,border-color .2s,transform .2s!important}[data-testid="stVerticalBlockBorderWrapper"]:hover{border-color:color-mix(in srgb,var(--ac-accent) 42%,var(--ac-border))!important;box-shadow:0 14px 36px var(--ac-shadow),0 0 22px color-mix(in srgb,var(--ac-accent) 7%,transparent)!important}
div[data-testid="stMetric"]{background:linear-gradient(145deg,var(--ac-surface3),var(--ac-surface))!important;border:1px solid var(--ac-border)!important;border-left:3px solid var(--ac-accent)!important;border-radius:10px!important;padding:14px 16px!important;box-shadow:0 7px 20px var(--ac-shadow),inset 0 1px 0 rgba(255,255,255,.04)!important}div[data-testid="stMetric"]:hover{transform:translateY(-2px);box-shadow:0 12px 26px var(--ac-shadow),0 0 18px color-mix(in srgb,var(--ac-accent) 12%,transparent)!important}[data-testid="stMetricLabel"]{color:var(--ac-muted)!important;font-size:10px!important;font-weight:800!important;text-transform:uppercase;letter-spacing:.1em}[data-testid="stMetricValue"]{color:var(--ac-text)!important;font-size:23px!important;font-weight:750!important}
div.stButton>button,div.stDownloadButton>button{min-height:39px;border-radius:7px;border:1px solid var(--ac-border-hi);background:linear-gradient(180deg,var(--ac-surface3),var(--ac-surface2));color:var(--ac-text);font-weight:650;box-shadow:0 3px 10px var(--ac-shadow);transition:all .18s}div.stButton>button:hover,div.stDownloadButton>button:hover{border-color:var(--ac-accent);color:var(--ac-accent);background:color-mix(in srgb,var(--ac-accent) 12%,var(--ac-surface2));box-shadow:0 0 0 3px color-mix(in srgb,var(--ac-accent) 10%,transparent),0 8px 18px var(--ac-shadow)}div.stButton>button[kind="primary"]{background:linear-gradient(135deg,var(--ac-accent),var(--ac-purple));border-color:transparent;color:#06121a;box-shadow:0 0 22px color-mix(in srgb,var(--ac-accent) 35%,transparent)}
div[data-testid="stSelectbox"]>div>div,div[data-baseweb="select"]>div,div[data-testid="stTextInput"] input{background:var(--ac-surface2)!important;border-color:var(--ac-border-hi)!important;color:var(--ac-text)!important;border-radius:7px!important}div[data-baseweb="select"] *{color:var(--ac-text)!important}
.check-row{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;margin:5px 0;background:linear-gradient(90deg,var(--ac-surface2),color-mix(in srgb,var(--ac-surface3) 70%,transparent));border:1px solid var(--ac-border);border-radius:6px;color:var(--ac-text);box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}.chip{min-width:68px;text-align:center;padding:3px 8px;border-radius:999px;font-size:9px;font-weight:800}.chip-pass{color:var(--ac-green);background:color-mix(in srgb,var(--ac-green) 13%,transparent);border:1px solid color-mix(in srgb,var(--ac-green) 34%,transparent)}.chip-fail{color:var(--ac-red);background:color-mix(in srgb,var(--ac-red) 13%,transparent);border:1px solid color-mix(in srgb,var(--ac-red) 34%,transparent)}
.banner{display:flex;gap:10px;padding:11px 14px;border-radius:8px;font-size:12px;margin-bottom:18px;box-shadow:0 5px 16px var(--ac-shadow)}.banner-ok{color:var(--ac-green);background:color-mix(in srgb,var(--ac-green) 11%,transparent);border:1px solid color-mix(in srgb,var(--ac-green) 28%,transparent)}.banner-alert{color:var(--ac-red);background:linear-gradient(90deg,color-mix(in srgb,var(--ac-red) 12%,transparent),color-mix(in srgb,var(--ac-amber) 8%,transparent));border:1px solid color-mix(in srgb,var(--ac-red) 30%,transparent)}.verdict{padding:11px 14px;border-radius:7px;background:var(--ac-surface2);border-left:3px solid var(--ac-accent);font-size:12px;color:var(--ac-text);line-height:1.55;margin-top:14px}
[data-testid="stSidebar"]{background:linear-gradient(180deg,var(--ac-surface),var(--ac-bg))!important;border-right:1px solid var(--ac-border)!important;box-shadow:6px 0 24px var(--ac-shadow)!important}[data-testid="stSidebar"]>div:first-child{padding:22px 18px!important}[data-testid="stSidebar"] h3{color:var(--ac-accent)!important;font-size:10px!important;text-transform:uppercase;letter-spacing:.14em;font-weight:800;margin:20px 0 10px!important}[data-testid="stSidebar"] *{color:var(--ac-text)}[data-testid="stSidebar"] [data-testid="stCaptionContainer"] *{color:var(--ac-muted)!important;font-size:11px!important}
[data-testid="stDataFrame"]{border:1px solid var(--ac-border);border-radius:8px;overflow:hidden}div[data-testid="stProgress"]>div>div{background:var(--ac-surface3)!important}div[data-testid="stProgress"]>div>div>div{background:linear-gradient(90deg,var(--ac-accent),var(--ac-purple))!important;box-shadow:0 0 12px color-mix(in srgb,var(--ac-accent) 35%,transparent)}.fineprint{color:var(--ac-muted)!important;font-size:10px;text-align:center;padding-top:28px;letter-spacing:.1em;font-weight:700;text-transform:uppercase}
@media(max-width:900px){[data-testid="stAppViewContainer"]>.main .block-container{padding:1rem}.brand-sub{display:none}.term-header{flex-wrap:wrap}}
"""


def apply_skin() -> None:
    theme = getattr(st.session_state, "theme", "dark")
    variables = LIGHT if theme == "light" else DARK
    st.markdown(f"<style>{variables}{CSS}</style>", unsafe_allow_html=True)
