# src/worlds.py
from __future__ import annotations

WORLD_MODES = {
    "synthetic_futures": {
        "label": "Synthetic Futures",
        "label_es": "Futuros Sintéticos",
        "icon": "◈",
        "accent": "#22d3ee",
        "accent_2": "#a78bfa",
        "background": "#080d16",
        "surface": "#131a24",
        "text": "#e8eef5",
        "muted": "#94a3b8",
        "plot_grid": "rgba(148,163,184,0.08)",
        "plot_bg": "rgba(15,20,28,0.68)",
        "hero": "Simulate futures. Expose fragility. Govern capital.",
        "hero_es": "Simule futuros. Exponga fragilidad. Gobierne capital.",
        "modules": {
            "overview": "The Atlas",
            "regimes": "The Flux",
            "generator": "The Forge",
            "risk": "The Veil",
            "validation": "The Parallax",
            "stress": "The Crucible",
            "protection": "The Threshold",
            "audit": "The Archive",
        },
    },
    "science_fiction": {
        "label": "Science Fiction Classics",
        "label_es": "Clásicos de Ciencia Ficción",
        "icon": "◇",
        "accent": "#f59e0b",
        "accent_2": "#a3e635",
        "background": "#0d0d0d",
        "surface": "#181713",
        "text": "#f4f1e7",
        "muted": "#b9af93",
        "plot_grid": "rgba(245,158,11,0.11)",
        "plot_bg": "rgba(24,23,19,0.72)",
        "hero": "Observe the system before the system observes you.",
        "hero_es": "Observe el sistema antes de que el sistema lo observe.",
        "modules": {
            "overview": "Foundation",
            "regimes": "Dune",
            "generator": "Solaris",
            "risk": "Dark Matter",
            "validation": "The Mirror",
            "stress": "The Trial",
            "protection": "Fahrenheit",
            "audit": "The Archive",
        },
    },
    "universe": {
        "label": "Universe Phenomena",
        "label_es": "Fenómenos del Universo",
        "icon": "✦",
        "accent": "#818cf8",
        "accent_2": "#e879f9",
        "background": "#050711",
        "surface": "#101126",
        "text": "#edf0ff",
        "muted": "#a8afcf",
        "plot_grid": "rgba(129,140,248,0.11)",
        "plot_bg": "rgba(16,17,38,0.75)",
        "hero": "Map the forces that bend the portfolio’s trajectory.",
        "hero_es": "Mapee las fuerzas que curvan la trayectoria del portafolio.",
        "modules": {
            "overview": "Constellation",
            "regimes": "Solar Winds",
            "generator": "Nebula Forge",
            "risk": "Event Horizon",
            "validation": "Twin Orbit",
            "stress": "Supernova Test",
            "protection": "Red Shift",
            "audit": "Flight Recorder",
        },
    },
    "abyssal": {
        "label": "Abyssal Systems",
        "label_es": "Sistemas Abisales",
        "icon": "◉",
        "accent": "#2dd4bf",
        "accent_2": "#60a5fa",
        "background": "#04131c",
        "surface": "#08202b",
        "text": "#e1f7f5",
        "muted": "#94c4c5",
        "plot_grid": "rgba(45,212,191,0.10)",
        "plot_bg": "rgba(8,32,43,0.74)",
        "hero": "Pressure reveals the structure beneath the surface.",
        "hero_es": "La presión revela la estructura bajo la superficie.",
        "modules": {
            "overview": "The Surface",
            "regimes": "The Current",
            "generator": "The Hatchery",
            "risk": "The Abyss",
            "validation": "The Thermocline",
            "stress": "Pressure Chamber",
            "protection": "Depth Gauge",
            "audit": "The Logbook",
        },
    },
    "executive": {
        "label": "Executive Minimal",
        "label_es": "Ejecutivo Minimal",
        "icon": "▣",
        "accent": "#2563eb",
        "accent_2": "#0f766e",
        "background": "#f7f8fa",
        "surface": "#ffffff",
        "text": "#172033",
        "muted": "#64748b",
        "plot_grid": "rgba(23,32,51,0.08)",
        "plot_bg": "rgba(255,255,255,0.92)",
        "hero": "Evidence-led portfolio oversight.",
        "hero_es": "Supervisión de portafolio basada en evidencia.",
        "modules": {
            "overview": "Portfolio Overview",
            "regimes": "Market Regimes",
            "generator": "Synthetic Markets",
            "risk": "Hidden Risk",
            "validation": "Reality Gap",
            "stress": "Robustness Testing",
            "protection": "Capital Protection",
            "audit": "Decision Trace",
        },
    },
}


def get_world(world_id: str) -> dict:
    return WORLD_MODES.get(world_id, WORLD_MODES["synthetic_futures"])
